config/routes.rb
Rails.application.routes.draw do

  resources :projects
  resources :observations
  resources :meetings
  resources :users

  devise_for :users, :path_prefix => 'profile', controllers: { registrations: 'users/registrations' }

  root 'projects#index'
end

app/views/assets/_messages.html.slim
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class=("alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}")
      button.close aria-hidden="true" data-dismiss="alert" type="button"  ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/assets/_nav.html.slim
nav.navbar.navbar-default.navbar-static-top role="navigation" style=("margin-bottom: 0")
  .navbar-header
    button.navbar-toggle data-target=".navbar-collapse" data-toggle="collapse" type="button"
      span.sr-only Toggle navigation
      span.icon-bar
      span.icon-bar
      span.icon-bar
    a.navbar-brand href="/"  FRIL - FNDR
  ul.nav.navbar-top-links.navbar-right.pull-right
    li.dropdown
      a.dropdown-toggle data-toggle="dropdown" href="#"
        i.fa.fa-user.fa-fw
        i.fa.fa-caret-down
      ul.dropdown-menu.dropdown-user
        li
          = link_to edit_user_registration_path do
            i.fa.fa-user.fa-fw
            |  Perfil
        li.divider
        li
          = link_to destroy_user_session_path, method: :delete do
            i.fa.fa-sign-out.fa-fw
            |  Cerrar sesión
  .navbar-default.sidebar role="navigation"
    .sidebar-nav.navbar-collapse
      ul#side-menu.nav.in
        li
          a href="/"
            i.fa.fa-dashboard.fa-fw
            |  Inicio
        - if current_user.has_role? :admin
          li
            a href="#"
              i.fa.fa-bar-chart-o.fa-fw
              |  Proyectos
              span.fa.arrow
            ul.nav.nav-second-level.collapse
              li
                = link_to 'Proyectos', projects_path()
              li
                = link_to 'Crear proyecto', new_project_path()
        - elsif current_user.has_role? :editor
          li
            a href="#"
              i.fa.fa-bar-chart-o.fa-fw
              |  Proyectos
              span.fa.arrow
            ul.nav.nav-second-level.collapse
              li
                = link_to 'Proyectos', projects_path()
              li
                = link_to 'Crear proyecto', new_project_path()
        - else
          li
            a href="#"
              i.fa.fa-bar-chart-o.fa-fw
              |  Proyectos
              span.fa.arrow
            ul.nav.nav-second-level.collapse
              li
                = link_to 'Proyectos', projects_path()
        - if current_user.has_role? :admin
          li
            a href="#"
              i.fa.fa-tasks.fa-fw
              |  Observaciones
              span.fa.arrow
            ul.nav.nav-second-level.collapse
              li
                = link_to 'Crear observación', new_observation_path()
        - elsif current_user.has_role? :editor
          li
            a href="#"
              i.fa.fa-tasks.fa-fw
              |  Observaciones
              span.fa.arrow
            ul.nav.nav-second-level.collapse
              li
                = link_to 'Crear observación', new_observation_path()
        - else
          li
        - if current_user.has_role? :admin
          li
            a href="#"
              i.fa.fa-users.fa-fw
              |  Usuarios
              span.fa.arrow
            ul.nav.nav-second-level.collapse
              li
                = link_to 'Usuarios', users_path()
              li
                = link_to 'Agregar usuario', new_user_path()

app/views/assets/_notification.html.slim
li.dropdown
  a.dropdown-toggle data-toggle="dropdown" href="#"
    i.fa.fa-bell.fa-fw
    i.fa.fa-caret-down
  ul.dropdown-menu.dropdown-alerts
    li
      a href="#"
        span.badge= @projects.notification_counter.size
        |   Proyecto sin seguimiento

app/views/assets/_title.html.slim
.row
  .col-lg-12
    h2.page-header= content_for?(:page_header) ? yield(:page_header) : "Dashboard"